---
title: "pythonhw1"
author: "Billy Wang"
date: "February 13, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 3


```{r part3}

# Task 10
rando = sample(1:100, 1, replace = TRUE)
print(rando)
if(rando >= 0 && rando <= 25){
  print("1st Quartile")
}else if(rando > 25 && rando <= 50) {
  print("2nd Quartile")
}else if(rando > 50 && rando <= 75){
  print("3rd Quartile")
}else if(rando > 75 && rando <= 100){
  print("4th Quartile")
}


```

## Part 4 & Part 5

You can also embed plots, for example:

```{r part4}

#Task 11
cities <- list("Tacoma", "Seattle", "Bellevue", "Kent", "Redmond", "Mercer Island")
for (city in cities)
    print(paste0("Warning,residents of ",city,",temperatures will reach sub-zero temperatures today, please stay indoors if possible"))


#Task 12 
library(stringr)

states <- list("Washington", "California", "Nevada", "Idaho", "Montana", "Utah", "Colorado", "New Mexico")
empty <- list()
for (state in states){
    currentPath = str_replace("U://Users/Zhang/Geog_458/filename.shp", "filename", state)
    print(currentPath)
    empty <- c(empty,currentPath)
}

# Task 13 
countdown <- function(num){
  count = num
  while(count > 0) {
    print(paste0("T-minus ",toString(count)))
    count = count - 1
  }
}
countdown(13)   
    
# Task 14
quartile <- function(num){
    if(num >= 0 && num<= 25)
        print("1st Quartile")
    else if (num > 25 && num <= 50)
        print("2nd Quartile")
    else if (num > 50 && num <= 75)
        print("3rd Quartile")
    else if (num > 75 && num <= 100)
        print("4th Quartile")
    else if (num < 0 || num > 100)
        print("Error")
}
quartile(13)
quartile(28)
quartile(66)
quartile(87)
quartile(-45)
quartile(132)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
